### ISSUE TITLE
weaveworks CNI, why not calico

### ISSUE THREAD

**Issue by walidshaari** [coolsvap/cks-prep#1]
Hi,
just checked your cluster prep. the CKS clusters are based on kubeadm and calico CNI plugin, why using weaveworks?

**Comment by coolsvap** [comment]
@walidshaari 

Thanks for your comment. No particular interest as such, I will include for calico as well!

**Comment by walidshaari** [comment]
Cool, we will add you to our curated CKS repo. should we add you to the exercises page?

**Comment by coolsvap** [comment]
sure!

**Comment by coolsvap** [comment]
Added support for calico as well! Closing the issue.
